services:
  - type: worker
    name: flexai-stock-monitor
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8656244864:AAHGAPZU_z59iyiJijNIVoYdRX-vyLI9H-4
      - key: TELEGRAM_CHAT_ID
        value: 8217905636
