services:
  - type: worker
    name: flexai-stock-monitor
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: TELEGRAM_ADMIN_CHAT_ID
        sync: false
      - key: KV_REST_API_URL
        sync: false
      - key: KV_REST_API_TOKEN
        sync: false
